BLACK = (0, 0, 0)
WHITE = (255,255,255)

#Screen settings
PROJECT_NAME = 'Prototype'
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

TILESIZE = 64
GRIDWIDTH = SCREEN_WIDTH / TILESIZE
GRIDHEIGHT = SCREEN_HEIGHT / TILESIZE

BGCOLOR = WHITE