#colors
BLACK = (0, 0, 0)
WHITE = (255,255,255)
RED = (255, 0, 0)

#Screen settings
PROJECT_NAME = 'Prototype'
SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
FPS = 60
MAP = 'map.txt'

TILESIZE = 64
GRIDWIDTH = SCREEN_WIDTH / TILESIZE
GRIDHEIGHT = SCREEN_HEIGHT / TILESIZE

BGCOLOR = BLACK
